export const VIEW_URL_MAP = {
  login: "/#/login",
  dashboard: "/#/dashboard",
  projects: "/#/projects",
  tasks: "/#/tasks",
  annotation: "/#/annotation",
  qa: "/#/qa",
  qaReview: "/#/qa-review",
  export: "/#/export",
  users: "/#/users",
  audit: "/#/audit",
  changePassword: "/#/change-password",
} as const;

export const VIEW_LABELS = {
  login: "Login",
  dashboard: "Dashboard Overview",
  projects: "Projects / PDF Import Setup",
  tasks: "Assigned tasks list",
  annotation: "Annotation workspace",
  qa: "Submitted reviews checklist (Queue)",
  qaReview: "Evaluation & QC decision desk",
  export: "CSV data export builder",
  users: "RBAC Users directory",
  audit: "System Audit logging",
  changePassword: "Change current profile password",
} as const;

export const TEST_IDS = {
  appShell: "app-shell",
  sidebar: "sidebar",
  primaryNav: "primary-nav",
  mainViewport: "main-viewport",
  profileMenuButton: "profile-menu-button",
  profileMenu: "profile-menu",
  profileChangePassword: "profile-change-password",
  profileLogout: "profile-logout",
  toastRegion: "toast-region",
  view: (name: keyof typeof VIEW_URL_MAP | string) => `view-${name}`,
  navLink: (name: string) => `nav-${name}`,
  roleSwitch: (role: string) => `role-switch-${role.toLowerCase()}`,
  loginEmail: "login-email",
  loginPassword: "login-password",
  loginSubmit: "login-submit",
  exportCreateForm: "export-create-form",
  exportProjectSelect: "export-project-select",
  exportBatchSelect: "export-batch-select",
  exportStatusSelect: "export-status-select",
  exportFormatSelect: "export-format-select",
  exportSubmit: "export-submit",
  exportHistoryTable: "export-history-table",
  exportDownloadButton: (jobId: string) => `export-download-${jobId}`,
  changePasswordForm: "change-password-form",
  currentPasswordInput: "current-password-input",
  newPasswordInput: "new-password-input",
  confirmPasswordInput: "confirm-password-input",
  changePasswordCancel: "change-password-cancel",
  changePasswordSubmit: "change-password-submit",
  dashboardMetricProjects: "dashboard-metric-projects",
  dashboardMetricSubmitted: "dashboard-metric-submitted",
  dashboardMetricApproved: "dashboard-metric-approved",
  dashboardMetricExports: "dashboard-metric-exports",
  dashboardOpenProjects: "dashboard-open-projects",
  dashboardOpenTasks: "dashboard-open-tasks",
  dashboardOpenAnnotation: "dashboard-open-annotation",
  dashboardOpenQa: "dashboard-open-qa",
  dashboardOpenExport: "dashboard-open-export",
  dashboardOpenAudit: "dashboard-open-audit",
  dashboardTaskTable: "dashboard-task-table",
  dashboardOpenAnnotationTask: (taskId: string) => `dashboard-open-annotation-${taskId}`,
  dashboardOpenQaTask: (taskId: string) => `dashboard-open-qa-${taskId}`,
  projectListPanel: "project-list-panel",
  projectListTable: "project-list-table",
  projectCreateNew: "project-create-new",
  projectBackDashboard: "project-back-dashboard",
  projectRow: (projectId: string) => `project-row-${projectId}`,
  projectDetailButton: (projectId: string) => `project-detail-${projectId}`,
  projectImportButton: (projectId: string) => `project-import-${projectId}`,
  projectWizardPanel: "project-wizard-panel",
  projectWizardStepper: "project-wizard-stepper",
  projectWizardStep: (stepNumber: number) => `project-wizard-step-${stepNumber}`,
  projectWizardPrev: "project-wizard-prev",
  projectWizardNext: "project-wizard-next",
  projectBackList: "project-back-list",
  projectWizardComplete: "project-wizard-complete",
  projectNameInput: "project-name-input",
  projectDeadlineInput: "project-deadline-input",
  projectDescriptionTextarea: "project-description-textarea",
  projectModalitySelect: "project-modality-select",
  projectLlmUrlInput: "project-llm-url-input",
  projectLlmApiKeyInput: "project-llm-api-key-input",
  projectLlmProviderSelect: "project-llm-provider-select",
  projectPromptTemplateTextarea: "project-prompt-template-textarea",
  projectUploadZone: "project-upload-zone",
  projectPdfFilesInput: "project-pdf-files-input",
  projectAnswerPdfChip: "project-answer-pdf-chip",
  projectSourceRefPdfChip: "project-source-ref-pdf-chip",
  projectSourceCountChip: "project-source-count-chip",
  projectUploadContinue: "project-upload-continue",
  projectBundleBuilderTable: "project-bundle-builder-table",
  projectValidateBundle: "project-validate-bundle",
  projectValidationPanel: "project-validation-panel",
  projectPreviewParse: "project-preview-parse",
  projectParsePreviewTable: "project-parse-preview-table",
  projectParseWarningBanner: "project-parse-warning-banner",
  projectConfirmImport: "project-confirm-import",
  projectPipelinePanel: "project-pipeline-panel",
  projectPipelineErrorPanel: "project-pipeline-error-panel",
  projectAssignmentNext: "project-assignment-next",
  projectAnnotator: (userSlug: string) => `project-annotator-${userSlug}`,
  projectQa: (userSlug: string) => `project-qa-${userSlug}`,
  projectAssignmentComplete: "project-assignment-complete",
  projectDetailPanel: "project-detail-panel",
  projectDetailTaskTable: "project-detail-task-table",
  projectDetailTaskRow: (taskId: string) => `project-detail-task-row-${taskId}`,
  tasksAssignedTable: "tasks-assigned-table",
  taskRow: (taskId: string) => `task-row-${taskId}`,
  taskOpenAnnotation: (taskId: string) => `task-open-annotation-${taskId}`,
  taskStatus: (taskId: string) => `task-status-${taskId}`,
  annotationBreadcrumb: "annotation-breadcrumb",
  annotationStatusBadge: "annotation-status-badge",
  annotationTimer: "annotation-timer",
  annotationReturnedWarning: "annotation-returned-warning",
  annotationAnswerPanel: "annotation-answer-panel",
  annotationQuestionText: "annotation-question-text",
  annotationAnswerText: "annotation-answer-text",
  annotationHighlightedClaim: "annotation-highlighted-claim",
  annotationScoringPanel: "annotation-scoring-panel",
  annotationResetClaim: "annotation-reset-claim",
  annotationClaimTextarea: "annotation-claim-textarea",
  annotationScore: (dimension: string) => `annotation-score-${dimension}`,
  annotationDelta: (dimension: string) => `annotation-delta-${dimension}`,
  annotationCompositeScore: "annotation-composite-score",
  annotationReasonTextarea: "annotation-reason-textarea",
  annotationNotesTextarea: "annotation-notes-textarea",
  annotationSubmit: "annotation-submit",
  annotationSourcePanel: "annotation-source-panel",
  annotationSourceCard: (sourceOrder: number | string) => `annotation-source-card-${sourceOrder}`,
  annotationSourceStatusSelect: "annotation-source-status-select",
  annotationSourceNoteTextarea: "annotation-source-note-textarea",
  annotationReferenceTab: (tab: string) => `annotation-reference-tab-${tab}`,
  annotationReferenceContent: "annotation-reference-content",
  qaFilterSubmitted: "qa-filter-submitted",
  qaFilterReturned: "qa-filter-returned",
  qaFilterApproved: "qa-filter-approved",
  qaFilterAll: "qa-filter-all",
  qaSearchInput: "qa-search-input",
  qaQueueTable: "qa-queue-table",
  qaEmptyState: "qa-empty-state",
  qaRow: (taskId: string) => `qa-row-${taskId}`,
  qaReviewOpen: (taskId: string) => `qa-review-open-${taskId}`,
  qaStatus: (taskId: string) => `qa-status-${taskId}`,
  qaReviewBreadcrumb: "qa-review-breadcrumb",
  qaBackQueue: "qa-back-queue",
  qaReviewStatusBadge: "qa-review-status-badge",
  qaReviewTab: (tab: string) => `qa-review-tab-${tab}`,
  qaBaselinePanel: "qa-baseline-panel",
  qaAnnotatorOutputPanel: "qa-annotator-output-panel",
  qaDeltaPanel: "qa-delta-panel",
  qaClaimDetailPanel: "qa-claim-detail-panel",
  qaSourceDetailPanel: "qa-source-detail-panel",
  qaApprove: "qa-approve",
  qaReturnOpen: "qa-return-open",
  qaHistoryTimeline: "qa-history-timeline",
  qaReturnModal: "qa-return-modal",
  qaReturnClose: "qa-return-close",
  qaReturnTypeSelect: "qa-return-type-select",
  qaReturnCommentTextarea: "qa-return-comment-textarea",
  qaReturnCancel: "qa-return-cancel",
  qaReturnConfirm: "qa-return-confirm",
  usersTable: "users-table",
  usersRow: (userSlug: string) => `users-row-${userSlug}`,
  usersRole: (userSlug: string) => `users-role-${userSlug}`,
  usersStatus: (userSlug: string) => `users-status-${userSlug}`,
  auditTable: "audit-table",
  auditRow: (auditId: string) => `audit-row-${auditId}`,
  auditAction: (auditId: string) => `audit-action-${auditId}`,
  auditEntity: (auditId: string) => `audit-entity-${auditId}`,
} as const;

export const toTestSlug = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
