"""initial schema

Revision ID: cbf57c0cefd7
Revises:
Create Date: 2026-06-08 16:25:22.169579
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "cbf57c0cefd7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("project_code", sa.String(length=64), nullable=False),
        sa.Column("project_name", sa.String(length=200), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("project_type", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_project_code"), "project", ["project_code"], unique=True)
    op.create_table(
        "user_account",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_account_email"), "user_account", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("before_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action_type"), "audit_log", ["action_type"], unique=False)
    op.create_index(op.f("ix_audit_log_project_id"), "audit_log", ["project_id"], unique=False)
    op.create_index(op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "batch",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("batch_name", sa.String(length=200), nullable=False),
        sa.Column("import_type", sa.String(length=32), nullable=False),
        sa.Column("total_bundles", sa.Integer(), nullable=False),
        sa.Column("valid_bundles", sa.Integer(), nullable=False),
        sa.Column("invalid_bundles", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batch_project_id"), "batch", ["project_id"], unique=False)
    op.create_table(
        "rubric_version",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version_name", sa.String(length=64), nullable=False),
        sa.Column("dimensions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rubric_version_project_id"), "rubric_version", ["project_id"], unique=False
    )
    op.create_table(
        "user_project_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_id", "role", name="uq_user_project_role"),
    )
    op.create_index(
        op.f("ix_user_project_role_project_id"), "user_project_role", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_project_role_user_id"), "user_project_role", ["user_id"], unique=False
    )
    op.create_table(
        "pdf_bundle",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("bundle_name", sa.String(length=200), nullable=False),
        sa.Column("article_code", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("bundle_status", sa.String(length=32), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pdf_bundle_article_code"), "pdf_bundle", ["article_code"], unique=False
    )
    op.create_index(op.f("ix_pdf_bundle_batch_id"), "pdf_bundle", ["batch_id"], unique=False)
    op.create_table(
        "parent_task",
        sa.Column("bundle_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("article_code", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("tier", sa.String(length=32), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("created_date", sa.Date(), nullable=True),
        sa.Column("answer_text_normalized", sa.Text(), nullable=True),
        sa.Column("answer_reference", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("total_claims", sa.Integer(), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["bundle_id"], ["pdf_bundle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parent_task_article_code"), "parent_task", ["article_code"], unique=False
    )
    op.create_index(op.f("ix_parent_task_batch_id"), "parent_task", ["batch_id"], unique=False)
    op.create_index(op.f("ix_parent_task_bundle_id"), "parent_task", ["bundle_id"], unique=False)
    op.create_table(
        "pdf_file",
        sa.Column("bundle_id", sa.Uuid(), nullable=False),
        sa.Column("file_role", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bundle_id"], ["pdf_bundle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pdf_file_bundle_id"), "pdf_file", ["bundle_id"], unique=False)
    op.create_table(
        "pdf_parse_result",
        sa.Column("bundle_id", sa.Uuid(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("answer_text_raw", sa.Text(), nullable=True),
        sa.Column("answer_text_normalized", sa.Text(), nullable=True),
        sa.Column(
            "metadata_extracted_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "source_list_extracted_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("parse_warnings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bundle_id"], ["pdf_bundle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pdf_parse_result_bundle_id"), "pdf_parse_result", ["bundle_id"], unique=False
    )
    op.create_table(
        "claim_task",
        sa.Column("parent_task_id", sa.Uuid(), nullable=False),
        sa.Column("claim_order", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(length=255), nullable=True),
        sa.Column("claim_text_original", sa.Text(), nullable=False),
        sa.Column("claim_text_final", sa.Text(), nullable=True),
        sa.Column("citation_markers", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("assigned_annotator_id", sa.Uuid(), nullable=True),
        sa.Column("rubric_version", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_annotator_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(["parent_task_id"], ["parent_task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_task_id", "claim_order", name="uq_claim_order_per_parent"),
    )
    op.create_index(
        op.f("ix_claim_task_assigned_annotator_id"),
        "claim_task",
        ["assigned_annotator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_task_parent_task_id"), "claim_task", ["parent_task_id"], unique=False
    )
    op.create_index(op.f("ix_claim_task_status"), "claim_task", ["status"], unique=False)
    op.create_table(
        "source_reference",
        sa.Column("parent_task_id", sa.Uuid(), nullable=False),
        sa.Column("source_order", sa.Integer(), nullable=False),
        sa.Column("source_title", sa.String(length=1000), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("source_text_extract", sa.Text(), nullable=True),
        sa.Column("source_parse_status", sa.String(length=32), nullable=False),
        sa.Column("access_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["parent_task_id"], ["parent_task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["pdf_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_task_id", "source_order", name="uq_source_order_per_parent"),
    )
    op.create_index(
        op.f("ix_source_reference_parent_task_id"),
        "source_reference",
        ["parent_task_id"],
        unique=False,
    )
    op.create_table(
        "annotation_submission",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("annotator_id", sa.Uuid(), nullable=False),
        sa.Column("sf", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("sc", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("hr", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("sq", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rel", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("comp", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("composite_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("source_access_status", sa.String(length=48), nullable=True),
        sa.Column("annotator_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotator_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claim_task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotation_submission_annotator_id"),
        "annotation_submission",
        ["annotator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_submission_claim_id"),
        "annotation_submission",
        ["claim_id"],
        unique=False,
    )
    op.create_table(
        "claim_source_map",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_method", sa.String(length=32), nullable=True),
        sa.Column("mapping_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("is_primary_source", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claim_task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source_reference.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "source_id", name="uq_claim_source"),
    )
    op.create_index(
        op.f("ix_claim_source_map_claim_id"), "claim_source_map", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_source_map_source_id"), "claim_source_map", ["source_id"], unique=False
    )
    op.create_table(
        "llm_pre_score",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("sf", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("sc", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("hr", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("sq", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rel", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("comp", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("composite_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("rationale_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claim_task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_pre_score_claim_id"), "llm_pre_score", ["claim_id"], unique=False)
    op.create_table(
        "qa_review",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("qa_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("error_category", sa.String(length=48), nullable=True),
        sa.Column("qa_comment", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claim_task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["qa_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_review_claim_id"), "qa_review", ["claim_id"], unique=False)
    op.create_index(op.f("ix_qa_review_qa_id"), "qa_review", ["qa_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qa_review_qa_id"), table_name="qa_review")
    op.drop_index(op.f("ix_qa_review_claim_id"), table_name="qa_review")
    op.drop_table("qa_review")
    op.drop_index(op.f("ix_llm_pre_score_claim_id"), table_name="llm_pre_score")
    op.drop_table("llm_pre_score")
    op.drop_index(op.f("ix_claim_source_map_source_id"), table_name="claim_source_map")
    op.drop_index(op.f("ix_claim_source_map_claim_id"), table_name="claim_source_map")
    op.drop_table("claim_source_map")
    op.drop_index(op.f("ix_annotation_submission_claim_id"), table_name="annotation_submission")
    op.drop_index(op.f("ix_annotation_submission_annotator_id"), table_name="annotation_submission")
    op.drop_table("annotation_submission")
    op.drop_index(op.f("ix_source_reference_parent_task_id"), table_name="source_reference")
    op.drop_table("source_reference")
    op.drop_index(op.f("ix_claim_task_status"), table_name="claim_task")
    op.drop_index(op.f("ix_claim_task_parent_task_id"), table_name="claim_task")
    op.drop_index(op.f("ix_claim_task_assigned_annotator_id"), table_name="claim_task")
    op.drop_table("claim_task")
    op.drop_index(op.f("ix_pdf_parse_result_bundle_id"), table_name="pdf_parse_result")
    op.drop_table("pdf_parse_result")
    op.drop_index(op.f("ix_pdf_file_bundle_id"), table_name="pdf_file")
    op.drop_table("pdf_file")
    op.drop_index(op.f("ix_parent_task_bundle_id"), table_name="parent_task")
    op.drop_index(op.f("ix_parent_task_batch_id"), table_name="parent_task")
    op.drop_index(op.f("ix_parent_task_article_code"), table_name="parent_task")
    op.drop_table("parent_task")
    op.drop_index(op.f("ix_pdf_bundle_batch_id"), table_name="pdf_bundle")
    op.drop_index(op.f("ix_pdf_bundle_article_code"), table_name="pdf_bundle")
    op.drop_table("pdf_bundle")
    op.drop_index(op.f("ix_user_project_role_user_id"), table_name="user_project_role")
    op.drop_index(op.f("ix_user_project_role_project_id"), table_name="user_project_role")
    op.drop_table("user_project_role")
    op.drop_index(op.f("ix_rubric_version_project_id"), table_name="rubric_version")
    op.drop_table("rubric_version")
    op.drop_index(op.f("ix_batch_project_id"), table_name="batch")
    op.drop_table("batch")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_project_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action_type"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_project_project_code"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
